blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://ferdium.org/faq
    about: The FAQ answers the most frequently asked questions on Ferdium
  - name: Main issue tracker
    url: https://github.com/ferdium/ferdium-app/issues
    about: Please log any issue in the main issue tracker, by selecting the relevant category
